name: Kiểm tra kết nối SSH đến Server

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Thiết lập SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATEY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 103.7.43.118 >> ~/.ssh/known_hosts
    - name: Kiểm tra kết nối SSH
      run: |
        ssh -i ~/.ssh/id_rsa -o "StrictHostKeyChecking=no" root@103.7.43.118 "echo 'Kết nối thành công!'"



        
