name: Deploy to Production

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 103.7.43.118
          username: nhathuyd4hp
          password: Nh@thuyd4hp
          script: whoami
