name: Remote SSH Command
on: 
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using key
        uses: appleboy/ssh-action@v1
        with:
          host: 103.7.43.118
          username: root
          key: ${{ secrets.SSH_PRIVATEY_KEY }}
          port: 22
          script: whoami
      
